/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PrivateChat;

import LogIn.iChatUser;
import Program.ClosePrivateWindowManager;
import Program.iChatIOManager;
import java.text.DateFormat;
import javax.swing.JFrame;

/**
 *
 * @author a8756
 */
public class iChatPrivateChatUI extends javax.swing.JFrame {
    private iChatIOManager ioManager;                            //主程序模块
    private iChatUser targetUser;                           //目标用户
    private ClosePrivateWindowManager closeWindowManager;   //私聊窗口关闭管理器
    

    /**
     * Creates new form iChatPrivateChatUI
     */
    public iChatPrivateChatUI(iChatIOManager ioManager, iChatUser targetUser, ClosePrivateWindowManager manager) {
        this.targetUser = targetUser;
        this.ioManager = ioManager;
        this.closeWindowManager = manager;
        closeWindowManager.setTargetUser(targetUser);
        
        initComponents();
        setTitle("您正在和" + targetUser.getUserName() + "聊天");
        targetLabel.setText(targetUser.getUserName() + "(" + targetUser.getUserID() + ")");
        this.setVisible(true);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public void setReceiveAreaMsg(iChatMessage msg) {
        iChatUser user= msg.getSource();
        DateFormat dateFormat = DateFormat.getDateTimeInstance();
        String timeString = dateFormat.format(msg.getMsgSendTime());
        receiveArea.append(user.getUserName() + "(" + user.getUserID() + "): " + timeString + "\n");
        receiveArea.append(msg.getMsg() + "\n");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        sendArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        receiveArea = new javax.swing.JTextArea();
        sendBt = new javax.swing.JButton();
        closeBt = new javax.swing.JButton();
        targetLabel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(700, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        sendArea.setColumns(20);
        sendArea.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        sendArea.setRows(5);
        jScrollPane1.setViewportView(sendArea);

        receiveArea.setEditable(false);
        receiveArea.setColumns(20);
        receiveArea.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        receiveArea.setRows(5);
        jScrollPane2.setViewportView(receiveArea);

        sendBt.setText("发送");
        sendBt.setPreferredSize(new java.awt.Dimension(65, 23));
        sendBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendBtMouseClicked(evt);
            }
        });

        closeBt.setText("关闭");
        closeBt.setPreferredSize(new java.awt.Dimension(65, 23));
        closeBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtMouseClicked(evt);
            }
        });

        targetLabel.setEditable(false);
        targetLabel.setFont(new java.awt.Font("微软雅黑", 0, 22)); // NOI18N
        targetLabel.setText("好友名称");
        targetLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                targetLabelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(targetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 222, Short.MAX_VALUE)
                                .addComponent(closeBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sendBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(targetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void targetLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targetLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_targetLabelActionPerformed

    private void closeBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtMouseClicked
        // 点击关闭按钮
        this.dispose();
        closeWindowManager.notifyLoginListeners();
    }//GEN-LAST:event_closeBtMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // 关闭窗口
        this.dispose();
        closeWindowManager.notifyLoginListeners();
    }//GEN-LAST:event_formWindowClosing

    private void sendBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendBtMouseClicked
        // 点击发送按钮
        ioManager.sendMessage(new iChatMessage(targetUser, ioManager.getUser(), sendArea.getText()));
        sendArea.setText("");    //清空输入框
    }//GEN-LAST:event_sendBtMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea receiveArea;
    private javax.swing.JTextArea sendArea;
    private javax.swing.JButton sendBt;
    private javax.swing.JTextField targetLabel;
    // End of variables declaration//GEN-END:variables
}
