/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GroupChat;

import LogIn.iChatUser;
import PrivateChat.iChatMessage;
import Program.iChatFriendsListModel;
import Program.iChatIOManager;
import Program.iChatUserListRenderer;
import java.awt.BorderLayout;
import java.text.DateFormat;
import java.util.HashSet;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JScrollPane;


/**
 * 群聊窗口
 * @author a8756
 */
public class iChatGroupChatUI extends javax.swing.JFrame {
    private iChatIOManager ioManager;       //IO管理
    private iChatUser myself;               //当前登陆用户
    private JList onlineList;               //在线用户列表
    private iChatFriendsListModel friendsListModel; 
    
    /**
     * Creates new form iChatGroupChatUI
     */
    public iChatGroupChatUI(iChatUser myself, iChatIOManager ioManager, HashSet<iChatUser> onlineListSet) {
        this.myself = myself;
        this.ioManager = ioManager;
        initComponents();
        
        friendsListModel = new iChatFriendsListModel(onlineListSet);
        onlineList = new JList(friendsListModel);
        onlineList.setCellRenderer(new iChatUserListRenderer());
        onlineList.setSize(onlineListPanel.getWidth(), onlineListPanel.getHeight());

        /*添加滚动条*/
        JScrollPane jp = new JScrollPane(onlineList);
        jp.setSize(onlineListPanel.getWidth(), onlineListPanel.getHeight());
        
        onlineListPanel.setLayout(new BorderLayout());
        onlineListPanel.add(jp,BorderLayout.CENTER);
        
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    /**
     * 更新群聊窗口中在线用户
     * @param newList 
     */
    public void updateOnlineList(HashSet<iChatUser> newList) {
        friendsListModel = new iChatFriendsListModel(newList);
        onlineList.setModel(friendsListModel);
    }
    
    /**
     * 显示消息到消息接收文本框
     * @param msg 
     */
    public void showMessage(iChatMessage msg) {
        iChatUser source = msg.getSource();
        DateFormat dateFormat = DateFormat.getDateTimeInstance();
        String timeString = dateFormat.format(msg.getMsgSendTime());
        receiveArea.append(source.getUserName() + "(" + source.getUserID() + "): " + timeString + "\n");
        receiveArea.append(msg.getMsg() + "\n");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        inputArea = new javax.swing.JTextArea();
        sendBt = new javax.swing.JButton();
        closeBt = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        receiveArea = new javax.swing.JTextArea();
        numbersLabel = new javax.swing.JTextField();
        onlineListPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("iChat聊天室");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(700, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        inputArea.setColumns(20);
        inputArea.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        inputArea.setRows(5);
        jScrollPane1.setViewportView(inputArea);

        sendBt.setText("发送");
        sendBt.setPreferredSize(new java.awt.Dimension(65, 23));
        sendBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendBtMouseClicked(evt);
            }
        });

        closeBt.setText("关闭");
        closeBt.setPreferredSize(new java.awt.Dimension(65, 23));
        closeBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtMouseClicked(evt);
            }
        });

        receiveArea.setEditable(false);
        receiveArea.setColumns(20);
        receiveArea.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        receiveArea.setRows(5);
        jScrollPane2.setViewportView(receiveArea);

        numbersLabel.setEditable(false);
        numbersLabel.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        numbersLabel.setText("群聊成员");
        numbersLabel.setPreferredSize(new java.awt.Dimension(80, 30));
        numbersLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbersLabelActionPerformed(evt);
            }
        });

        onlineListPanel.setBackground(new java.awt.Color(153, 255, 153));
        onlineListPanel.setPreferredSize(new java.awt.Dimension(150, 0));

        javax.swing.GroupLayout onlineListPanelLayout = new javax.swing.GroupLayout(onlineListPanel);
        onlineListPanel.setLayout(onlineListPanelLayout);
        onlineListPanelLayout.setHorizontalGroup(
            onlineListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        onlineListPanelLayout.setVerticalGroup(
            onlineListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(156, Short.MAX_VALUE)
                        .addComponent(closeBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sendBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                        .addGap(15, 15, 15)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(onlineListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numbersLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numbersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(onlineListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numbersLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbersLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numbersLabelActionPerformed

    private void closeBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtMouseClicked
        //关闭群聊对话框
        this.dispose();
    }//GEN-LAST:event_closeBtMouseClicked

    private void sendBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendBtMouseClicked
        //发送按钮
        String msg = inputArea.getText();
        if (msg != null) {
            ioManager.sendMessage(new iChatMessage(myself,msg,iChatMessage.GROUP_MESSAGE));
        }
        inputArea.setText("");
    }//GEN-LAST:event_sendBtMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // 窗口右上角关闭按钮
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBt;
    private javax.swing.JTextArea inputArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField numbersLabel;
    private javax.swing.JPanel onlineListPanel;
    private javax.swing.JTextArea receiveArea;
    private javax.swing.JButton sendBt;
    // End of variables declaration//GEN-END:variables
}
