/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LogIn;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author a8756
 */
public class LoginUI extends javax.swing.JFrame {
    private iChatUser user = null;      //当前登陆用户
    private iChatLogin loginModel;      //登陆模块
    
    public void addLoginListener(LoginListener listener) {
        loginModel.addLoginListener(listener);
    }
    /**
     * Creates new form iChatLogIn
     */
    public LoginUI() {
        this.loginModel = new iChatLogin();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameField = new javax.swing.JTextField();
        passwdField = new javax.swing.JPasswordField();
        nameLabel = new javax.swing.JLabel();
        passwdLabel = new javax.swing.JLabel();
        signInLabel = new javax.swing.JLabel();
        setPasswdLabel = new javax.swing.JLabel();
        logInButton = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        iChatLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(420, 330));
        setMinimumSize(new java.awt.Dimension(420, 330));
        setPreferredSize(new java.awt.Dimension(420, 330));
        setSize(new java.awt.Dimension(420, 330));

        nameField.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameLabel.setText("用户ID");

        passwdLabel.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        passwdLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passwdLabel.setText("密码");

        signInLabel.setText("新用户注册");
        signInLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signInLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signInLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signInLabelMouseExited(evt);
            }
        });

        setPasswdLabel.setText("忘记密码？");
        setPasswdLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setPasswdLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                setPasswdLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                setPasswdLabelMouseExited(evt);
            }
        });

        logInButton.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        logInButton.setText("登陆");
        logInButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logInButtonMouseClicked(evt);
            }
        });

        welcomeLabel.setFont(new java.awt.Font("微软雅黑", 0, 36)); // NOI18N
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText("欢迎使用");

        iChatLabel.setFont(new java.awt.Font("Old English Text MT", 1, 36)); // NOI18N
        iChatLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iChatLabel.setText("iChat");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(passwdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(logInButton, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(passwdField)
                            .addComponent(nameField))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(signInLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(setPasswdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(welcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iChatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(iChatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signInLabel))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(passwdField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(setPasswdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(passwdLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(logInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void logInButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logInButtonMouseClicked
        /**
         * 点击登陆按钮，将用户名和密码创建为一个User对象
         * 查询服务器用户信息
         */
        String userID;
        String passwdString;
        char[] passwd;
        userID = nameField.getText();
        passwd = passwdField.getPassword();
        passwdString = String.valueOf(passwd);
        user = new iChatUser(Long.parseLong(userID),passwdString);
        loginModel.setUser(user);
        
        //登陆
        loginModel.login();

    }//GEN-LAST:event_logInButtonMouseClicked

    private void signInLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInLabelMouseClicked
        /**
         * 新用户注册
         */
        SignInUI signIn = new SignInUI();
        signIn.setDefaultCloseOperation(SignInUI.HIDE_ON_CLOSE);
        signIn.setVisible(true);
    }//GEN-LAST:event_signInLabelMouseClicked

    private void setPasswdLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setPasswdLabelMouseClicked
        // 忘记密码？ 我也帮不了啊！
        JOptionPane.showMessageDialog(this, "忘记密码？我也帮不了你啊！！！");
    }//GEN-LAST:event_setPasswdLabelMouseClicked

    private void signInLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInLabelMouseEntered
        // 鼠标进入，则将字体变为蓝色加粗下划线
        signInLabel.setFont(new Font("宋体",1,12));
        signInLabel.setForeground(Color.BLUE);
    }//GEN-LAST:event_signInLabelMouseEntered

    private void signInLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInLabelMouseExited
        // 鼠标离开，恢复原来字体
        signInLabel.setFont(new Font("宋体",0,12));
        signInLabel.setForeground(Color.BLACK);
    }//GEN-LAST:event_signInLabelMouseExited

    private void setPasswdLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setPasswdLabelMouseEntered
        // 鼠标进入，则将字体变为蓝色加粗下划线
        setPasswdLabel.setFont(new Font("宋体",1,12));
        setPasswdLabel.setForeground(Color.BLUE);
    }//GEN-LAST:event_setPasswdLabelMouseEntered

    private void setPasswdLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setPasswdLabelMouseExited
        // 鼠标离开，恢复原来字体
        setPasswdLabel.setFont(new Font("宋体",0,12));
        setPasswdLabel.setForeground(Color.BLACK);
    }//GEN-LAST:event_setPasswdLabelMouseExited
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUI().setVisible(true);
            }
        });
    }

    public iChatUser getUser() {
        return user;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iChatLabel;
    private javax.swing.JButton logInButton;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPasswordField passwdField;
    private javax.swing.JLabel passwdLabel;
    private javax.swing.JLabel setPasswdLabel;
    private javax.swing.JLabel signInLabel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
